let name=prompt("What is your name?")
const text= document.querySelector(".text")
const inpName = document.getElementById("inpName");
const inpPassword = document.getElementById("inpPassword");
const btnSign = document.getElementById("btnSign");
const mainform= document.getElementById("mainform")
const inpAdd = document.getElementById("inpAdd");
const inpDraw = document.getElementById("inpDraw");
const inpShow = document.getElementById("inpShow");
const maindiv=document.querySelector("#mainDiv")
const divBalance = document.querySelector("#divBalance")
text.innerHTML= `${name}! Welcome to Money bank`